<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>QTYInCart</name>
   <tag></tag>
   <elementGuidId>bfdc6440-488c-4229-808b-d1aeab4f8e76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[data-test-selector=&quot;cartline_qty&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
